services:
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc
    restart: unless-stopped
    ports:
      - 8053:8042
      - 4242:4242
    volumes:
      - orthanc-storage:/var/lib/orthanc/db/
    environment:
      ORTHANC__NAME: "PACS Orthanc"
      ORTHANC__DICOM_AET: "PACS_AI"
      ORTHANC__DICOM_PORT: 4242
      ORTHANC__DICOM_MODALITIES: |
        {
          "hospital-1": ["HOSPITAL_1", "orthanc-hospital-1", 4242],
          "hospital-2": ["HOSPITAL_2", "orthanc-hospital-2", 4242]
        }
      ORTHANC__DICOM_MODALITIES_IN_DATABASE: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__ORTHANC_EXPLORER_2__ENABLE: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "false"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "http://localhost/orthanc/ohif/"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "false"
      OHIF_PLUGIN_ENABLED: "false"
      ORTHANC__OHIF: |
        {
          "RouterBasename": "/orthanc/ohif/",
          "DataSource" : "dicom-web"
        }
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__POSTGRESQL: |
        {
          "Host": "orthanc-index"
        }
      ORTHANC__CONCURRENT_JOBS: 16
      ORTHANC__STORAGE_COMPRESSION: "false"
      ORTHANC__LIMIT_FIND_RESULTS: 100
      ORTHANC__KEEP_ALIVE: "true"
      ORTHANC__TCP_NO_DELAY: "true"
      VERBOSE_STARTUP: "true"
    depends_on:
      - orthanc-index

  orthanc-index:
    image: postgres:latest
    container_name: orthanc-index
    restart: unless-stopped
    ports: ["5432:5432"]
    volumes: ["orthanc-index:/var/lib/postgresql/data"]
    command: -c 'max_connections=200'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  orthanc-storage:
  orthanc-index:
