services:
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc
    restart: unless-stopped
    expose:
      - "4242"
    volumes:
      - orthanc-storage:/var/lib/orthanc/db/
    environment:
      ORTHANC__NAME: "PACS Orthanc"
      ORTHANC__DICOM_AET: "PACS_AI"
      # Need to manualy update ORTHANC__DICOM_MODALITIES for now
      ORTHANC__DICOM_MODALITIES: |
        {
          "${FIREBASE_AET_1}": ["${PACS_AET_1}", "${PACS_IP_1}", ${PACS_PORT_1}] 
        }
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "http://localhost/orthanc/ohif/"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC__OHIF: |
        {
          "RouterBasename": "/orthanc/ohif/",
          "DataSource" : "dicom-web"
        }
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      ORTHANC__POSTGRESQL: |
        {
          "Host": "orthanc-index"
        }
      ORTHANC__CONCURRENT_JOBS: 16
      ORTHANC__STORAGE_COMPRESSION: "false"
      ORTHANC__LIMIT_FIND_RESULTS: 100
      ORTHANC__KEEP_ALIVE: "true"
      ORTHANC__TCP_NO_DELAY: "true"
      VERBOSE_STARTUP: "true"
    depends_on:
      - orthanc-index

  orthanc-index:
    image: postgres:latest
    container_name: orthanc-index
    restart: unless-stopped
    expose:
      - "5432"
    volumes: ["orthanc-index:/var/lib/postgresql/data"]
    command: -c 'max_connections=200'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  orthanc-storage:
  orthanc-index:
