networks:
  default:
    name: pacs-net

include:
  - orthanc/docker-compose.yml
  # - orthanc-pacs/docker-compose.yml # uncomment to launch othanc pacs for simulation
  - redis/docker-compose.yml
  - elasticsearch/docker-compose.yml
  - api-pacs/docker-compose.yml
  - ../PACS-AI/docker-compose.yml
  - torchserve/docker-compose.yml
  - nginx/docker-compose.yml