[project]
name = "pacs-backend"
version = "0.1.0"
description = "PACS AI backend"
readme = "README.md"
requires-python = ">=3.10"
license = "CC0-1.0"

[tool.ruff]
line-length = 98
target-version = "py310"
fix = true

[tool.ruff.lint]
select = [
    "B", "C4", "DTZ", "F", "FLY", "G", "I",
    "PERF", "PIE", "RET", "SIM", "TID", "UP", "W"
]
ignore = ["E501", "S101", "PERF203"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pyupgrade]
keep-runtime-typing = true
py310-plus = true
