networks:
  pacs-net:
    external: true

services:
  orthanc-hospital-1:
    image: orthancteam/orthanc:latest
    container_name: orthanc-hospital-1
    restart: unless-stopped
    ports:
      - 8063:8042
    volumes:
      - orthanc-storage-hospital-1:/var/lib/orthanc/db/
    environment:
      ORTHANC__NAME: "Hospital 1 Orthanc"
      ORTHANC__DICOM_AET: "HOSPITAL_1"
      ORTHANC__DICOM_MODALITIES: |
        {
          "pacs-ai": ["PACS_AI", "orthanc", 4242]
        }
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "http://localhost/orthanc/ohif/"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC__OHIF: |
        {
          "RouterBasename": "/orthanc/ohif/",
          "DataSource" : "dicom-web"
        }
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      VERBOSE_STARTUP: "true"

  orthanc-hospital-2:
    image: orthancteam/orthanc:latest
    container_name: orthanc-hospital-2
    restart: unless-stopped
    ports:
      - 8073:8042
    volumes:
      - orthanc-storage-hospital-2:/var/lib/orthanc/db/
    environment:
      ORTHANC__NAME: "Hospital 2 Orthanc"
      ORTHANC__DICOM_AET: "HOSPITAL_2"
      ORTHANC__DICOM_MODALITIES: |
        {
          "pacs-ai": ["PACS_AI", "orthanc", 4242]
        }
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__DICOM_WEB__PUBLIC_ROOT: "/orthanc/dicom-web/"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER_3: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__OHIF_VIEWER_3_PUBLIC_ROOT: "http://localhost/orthanc/ohif/"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC__OHIF: |
        {
          "RouterBasename": "/orthanc/ohif/",
          "DataSource" : "dicom-web"
        }
      ORTHANC__AUTHENTICATION_ENABLED: "false"
      VERBOSE_STARTUP: "true"

volumes:
  orthanc-storage-hospital-1:
  orthanc-storage-hospital-2:
