services:
  orchestrator:
    build: .
    image: pacs-ai-backend-orchestrator
    container_name: orchestrator
    restart: unless-stopped
    expose:
      - "8585"
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOST=0.0.0.0
      - PORT=8585
      - RELOAD=False
      - API_BASE_URL=http://api-pacs:8080/v1
      # You can add other environment variables from .env file here
    networks:
      - pacs-net

networks:
  pacs-net:
    external: true
