server {
	listen 80;

	location /api/ {
		proxy_pass http://api-pacs:8000/; # Trailing slash is important to remove /api/ from the request
		proxy_set_header Host $http_host;
		proxy_request_buffering off;
		proxy_max_temp_file_size 0;
		client_max_body_size 0;

		# increase timeout to 300 seconds
		# https://stackoverflow.com/a/25929484
		proxy_connect_timeout       300;
		proxy_send_timeout          300;
		proxy_read_timeout          300;
		send_timeout                300;
	}

	# only in dev/staging
	# disable orthanc explorer (cannot be disabled in orthanc configs)
	location /orthanc/app/explorer.html {
		return 301 $scheme://$http_host/;
	}

	# only in dev/staging
	location /orthanc/ {
		proxy_pass http://orthanc:8042;
		rewrite /orthanc(.*) $1 break;
		proxy_set_header Host $http_host;
		proxy_request_buffering off;
		proxy_max_temp_file_size 0;
		client_max_body_size 0;

		# workaround for ohif cors
		add_header 'Access-Control-Allow-Origin' '*' always;
	}

	# only in dev/staging
	location /orthanc-hospital-1/ {
		proxy_pass http://orthanc-hospital-1:8042;
		rewrite /orthanc-hospital-1(.*) $1 break;
		proxy_set_header Host $http_host;
		proxy_request_buffering off;
		proxy_max_temp_file_size 0;
		client_max_body_size 0;

		# workaround for ohif cors
		add_header 'Access-Control-Allow-Origin' '*' always;
	}

	location /orthanc-hospital-2/ {
		proxy_pass http://orthanc-hospital-2:8042;
		rewrite /orthanc-hospital-2(.*) $1 break;
		proxy_set_header Host $http_host;
		proxy_request_buffering off;
		proxy_max_temp_file_size 0;
		client_max_body_size 0;

		# workaround for ohif cors
		add_header 'Access-Control-Allow-Origin' '*' always;
	}
}
