services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      - NGINX_API_MAX_BODY_SIZE=${NGINX_API_MAX_BODY_SIZE:-16m}
      - NGINX_DICOMWEB_MAX_BODY_SIZE=${NGINX_DICOMWEB_MAX_BODY_SIZE:-2g}
    depends_on:
      - orthanc
      - api-pacs
