networks:
  pacs-net:
    external: true

services:
  huggingface-downloader:
    container_name: huggingface-downloader
    build:
      context: ./models
      dockerfile: Dockerfile.prod
      args:
        HF_USERNAME: ${HF_USERNAME}
        HF_TOKEN: ${HF_TOKEN}
    volumes:
      - ./models:/models
    env_file:
      - .env

  torchserve:
    container_name: torchserve
    image: pytorch/torchserve:0.9.0-gpu
    command: torchserve --start --model-store /models/torch_serving_model --ts-config /models/torch_serving_model/config.properties
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - ./models:/models
    expose:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      huggingface-downloader:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "python3 -c 'import requests; response = requests.get(\"http://localhost:8080/ping\"); assert response.status_code == 200'"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s