services:
  api-pacs:
    env_file: .env
    environment:
      APP_TIMEZONE: ${APP_TIMEZONE:-America/Toronto}
      TZ: ${APP_TIMEZONE:-America/Toronto}
    build: .
    container_name: api-pacs
    restart: unless-stopped
    networks:
      - default
      - pacs-net
    ports:
      - ${API_URL_REST_PORT}:${API_URL_REST_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
      - elasticsearch
      - postgresql

networks:
  pacs-net:
    external: true
