networks:
  pacs-net:
    external: true

services:
  api-pacs:
    build: .
    container_name: api-pacs
    restart: unless-stopped
    expose:
      - ${API_URL_REST_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
      - elasticsearch
